/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueIndexRouteImport } from './routes/league.index'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league.$leagueId.index'
import { Route as LeagueLeagueIdWaiverRouteImport } from './routes/league.$leagueId.waiver'
import { Route as LeagueLeagueIdTeamRosterIdRouteImport } from './routes/league.$leagueId.team.$rosterId'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIndexRoute = LeagueIndexRouteImport.update({
  id: '/league/',
  path: '/league/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdWaiverRoute = LeagueLeagueIdWaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdTeamRosterIdRoute =
  LeagueLeagueIdTeamRosterIdRouteImport.update({
    id: '/team/$rosterId',
    path: '/team/$rosterId',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/sync': typeof SyncRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/': typeof LeagueIndexRoute
  '/league/$leagueId/waiver': typeof LeagueLeagueIdWaiverRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/team/$rosterId': typeof LeagueLeagueIdTeamRosterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/sync': typeof SyncRoute
  '/league': typeof LeagueIndexRoute
  '/league/$leagueId/waiver': typeof LeagueLeagueIdWaiverRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/team/$rosterId': typeof LeagueLeagueIdTeamRosterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/sync': typeof SyncRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/league/': typeof LeagueIndexRoute
  '/league/$leagueId/waiver': typeof LeagueLeagueIdWaiverRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/league/$leagueId/team/$rosterId': typeof LeagueLeagueIdTeamRosterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rankings'
    | '/sync'
    | '/league/$leagueId'
    | '/league/'
    | '/league/$leagueId/waiver'
    | '/league/$leagueId/'
    | '/league/$leagueId/team/$rosterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rankings'
    | '/sync'
    | '/league'
    | '/league/$leagueId/waiver'
    | '/league/$leagueId'
    | '/league/$leagueId/team/$rosterId'
  id:
    | '__root__'
    | '/'
    | '/rankings'
    | '/sync'
    | '/league/$leagueId'
    | '/league/'
    | '/league/$leagueId/waiver'
    | '/league/$leagueId/'
    | '/league/$leagueId/team/$rosterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingsRoute: typeof RankingsRoute
  SyncRoute: typeof SyncRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRouteWithChildren
  LeagueIndexRoute: typeof LeagueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/': {
      id: '/league/'
      path: '/league'
      fullPath: '/league/'
      preLoaderRoute: typeof LeagueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/waiver': {
      id: '/league/$leagueId/waiver'
      path: '/waiver'
      fullPath: '/league/$leagueId/waiver'
      preLoaderRoute: typeof LeagueLeagueIdWaiverRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/team/$rosterId': {
      id: '/league/$leagueId/team/$rosterId'
      path: '/team/$rosterId'
      fullPath: '/league/$leagueId/team/$rosterId'
      preLoaderRoute: typeof LeagueLeagueIdTeamRosterIdRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
  }
}

interface LeagueLeagueIdRouteChildren {
  LeagueLeagueIdWaiverRoute: typeof LeagueLeagueIdWaiverRoute
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
  LeagueLeagueIdTeamRosterIdRoute: typeof LeagueLeagueIdTeamRosterIdRoute
}

const LeagueLeagueIdRouteChildren: LeagueLeagueIdRouteChildren = {
  LeagueLeagueIdWaiverRoute: LeagueLeagueIdWaiverRoute,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
  LeagueLeagueIdTeamRosterIdRoute: LeagueLeagueIdTeamRosterIdRoute,
}

const LeagueLeagueIdRouteWithChildren = LeagueLeagueIdRoute._addFileChildren(
  LeagueLeagueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingsRoute: RankingsRoute,
  SyncRoute: SyncRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRouteWithChildren,
  LeagueIndexRoute: LeagueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
