/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as LeagueBoardRouteImport } from './routes/league-board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueBoardRoute = LeagueBoardRouteImport.update({
  id: '/league-board',
  path: '/league-board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/league-board': typeof LeagueBoardRoute
  '/rankings': typeof RankingsRoute
  '/sync': typeof SyncRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/league-board': typeof LeagueBoardRoute
  '/rankings': typeof RankingsRoute
  '/sync': typeof SyncRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/league-board': typeof LeagueBoardRoute
  '/rankings': typeof RankingsRoute
  '/sync': typeof SyncRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/league-board' | '/rankings' | '/sync' | '/league/$leagueId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/league-board' | '/rankings' | '/sync' | '/league/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/league-board'
    | '/rankings'
    | '/sync'
    | '/league/$leagueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeagueBoardRoute: typeof LeagueBoardRoute
  RankingsRoute: typeof RankingsRoute
  SyncRoute: typeof SyncRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league-board': {
      id: '/league-board'
      path: '/league-board'
      fullPath: '/league-board'
      preLoaderRoute: typeof LeagueBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeagueBoardRoute: LeagueBoardRoute,
  RankingsRoute: RankingsRoute,
  SyncRoute: SyncRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
